function madrid_2018_1 = importAirquality(filename, dataLines)
%IMPORTFILE7 Import data from a text file
%  MADRID_2018_1 = IMPORTFILE7(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a timetable.
%
%  MADRID_2018_1 = IMPORTFILE7(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  madrid_2018_1 = importfile7("C:\Users\lsammon\MATLAB Drive\1_Seminars\Enhancing Geoscience with MATLAB\Madrid_Air_Quality-main\madrid_2018.csv", [2, Inf]);
%
%  See also READTIMETABLE.
%
% Auto-generated by MATLAB on 05-Aug-2025 09:27:09

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["date", "BEN", "CH4", "CO", "EBE", "NMHC", "NO", "NO_2", "NOx", "O_3", "PM10", "PM25", "SO_2", "TCH", "TOL", "station"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
madrid_2018_1 = readtimetable(filename, opts, "RowTimes", "date");

end