function [fitresult, gof] = createFit1(CH4, CO)
%CREATEFIT1(CH4,CO)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: CH4 from airq
%      Y Output: CO from airq
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Aug-2025 11:41:54


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( CH4, CO );

% Set up fittype and options.
ft = fittype( 'logistic' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [2 1.66869441544499 2.4419300571118];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'CO vs. CH4', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'CH4', 'Interpreter', 'none' );
ylabel( 'CO', 'Interpreter', 'none' );
grid on


